"""
aalm_core.py — pure functions for the AALM front-end backend.

  * build_leggett_input(cfg) -> str   : structured config -> LeggettInput.txt text
  * read_out_csv(path)       -> dict  : parse Out_<name>.csv, downsample, summarize

No external dependencies. The exe invocation lives in model_runner.py so the model
execution can be swapped (e.g. for a Linux build or container) without touching this.

The output of build_leggett_input is byte-compatible with the validated reference
input (see backend/golden_TestEx2.txt and backend/test_core.py).
"""
from __future__ import annotations
import csv
import math
from typing import Any, Dict, List


# --------------------------------------------------------------------------- #
#  number / line formatting
# --------------------------------------------------------------------------- #
def num(v: Any) -> str:
    """Format a number with '.' decimals, no scientific notation, trimmed zeros."""
    if v is None or v == "":
        return "0"
    f = float(v)
    if f == int(f) and abs(f) < 1e15:
        return str(int(f))
    s = f"{f:.15f}".rstrip("0").rstrip(".")
    return s


def line(type_: str, name: str, values: List[Any]) -> str:
    """Produce 'Type,Name,nlev,v1,v2,...'."""
    parts = [type_, name, str(len(values))] + [num(v) for v in values]
    return ",".join(parts)


def years_to_days(years: Any) -> int:
    return int(round(float(years) * 365.0))


# canonical ordering used by the workbook output (kept identical so generated
# files match the reference exactly)
PC_ORDER = [
    "HCTB", "HCTA", "ASHWT", "BLDMOT", "BONIN", "BRANIN", "BRATIO", "CRTWT", "H1TOBL", "H1TOH2",
    "H1TOSI", "HEPIN", "IFETAL", "KWT", "PLSVOL", "POWER", "RBCIN", "RBCNL", "RBCVOL", "RENIN",
    "RKDN1", "RLLI", "RLVR1", "RPLAS", "RPROT", "RSIC", "RSOF0", "RSOF1", "RSOF2", "RSTMC", "RULI",
    "S2HAIR", "SATRAT", "SIZEVF", "SOFIN", "TBONEL", "TEVF", "TOFECE", "TOKDN1", "TOKDN2", "TOLVR1",
    "TOPROT", "TORBC", "TOSWET", "TOURIN", "TRBWT", "VBLC", "VKC", "VLC", "VLUC",
]
PV_ORDER = [
    "F1", "AMTBLD", "FLONG", "GSCAL", "RBLAD", "RBRAN", "RCORT", "RCS2B", "RCS2DF", "RDIFF", "RKDN2",
    "RLVR2", "RRBC", "RTRAB", "RTS2B", "RTS2DF", "TBONE", "TFRAC", "TOBRAN", "TOSOF0", "TOSOF1", "TOSOF2",
]
LUNG_ORDER = [
    "DepFracLET", "DepFracLTB", "DepFracLalv", "RLETplas", "RLETstom", "RLTBplas", "RLTBLET",
    "RLalvPlas", "RLalvLTB", "RLalvLint", "RLintPlas",
]
MEDIA_ORDER = [
    ("soil", "Soil", "conc"), ("dust", "Dust", "conc"), ("water", "Water", "conc"),
    ("air", "Air", "conc"), ("food", "Food", "amt"), ("other", "Other", "amt"),
]


def _g(obj: Any, key: str, default: Any = None) -> Any:
    """Read a key from a dict or attribute from an object."""
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


# --------------------------------------------------------------------------- #
#  input-file builder
# --------------------------------------------------------------------------- #
def build_leggett_input(cfg: Dict[str, Any]) -> str:
    L: List[str] = ["! LeggettInput.txt generated by the AALM browser front-end"]

    L.append(f"Name,{_g(cfg, 'simName')}")

    s = _g(cfg, "sim")
    L.append(line("Sim", "age_range", [years_to_days(_g(s, "ageMinYr")), years_to_days(_g(s, "ageMaxYr"))]))
    L.append(line("Sim", "steps_per_day", [_g(s, "stepsPerDay")]))
    L.append(line("Sim", "outwrite", [_g(s, "outwrite")]))
    L.append(line("Sim", "irbc", [_g(s, "irbc")]))
    L.append(line("Sim", "iterate", [_g(s, "iterate")]))
    L.append(line("Sim", "debug", [0]))
    L.append(line("Sim", "interp", [_g(s, "interp")]))

    g = _g(cfg, "growth")
    for k in ["sex", "wbirth", "wchild", "half", "wadult", "kappa", "lambda", "LB"]:
        L.append(line("Growth", k, [_g(g, k)]))

    pc = _g(cfg, "physConst")
    for k in PC_ORDER:
        L.append(line("Phys", k, [_g(pc, k)]))

    ages = list(_g(cfg, "physAges"))
    L.append(line("Phys", "Age", ages))
    pv = _g(cfg, "physTimeDep")
    for k in PV_ORDER:
        L.append(line("Phys", k, list(_g(pv, k))))

    lung = _g(cfg, "lung")
    for k in LUNG_ORDER:
        L.append(line("Lung", k, list(_g(lung, k))))

    media = _g(cfg, "media")
    for key, tok, mode in MEDIA_ORDER:
        md = _g(media, key)
        if md is None or not _g(md, "active") or int(_g(md, "sources", 0)) < 1:
            continue
        n = int(_g(md, "sources"))
        L.append(line(tok, "sources", [n]))

        if mode == "conc":
            conc_ages = [years_to_days(a) for a in _g(md, "concAgesYr")]
            L.append(line(tok, "conc_ages", conc_ages))
            concs = _g(md, "concs")
            for i in range(n):
                L.append(line(tok, f"concs{i + 1}", list(concs[i])))
            masks = _g(md, "masks") or []
            for mi, mask in enumerate(masks, start=1):
                L.append(line(tok, f"mask{mi}",
                              [_g(mask, "source"), _g(mask, "period"), _g(mask, "first"), _g(mask, "last")]))
            intake_ages = [years_to_days(a) for a in _g(md, "intakeAgesYr")]
            L.append(line(tok, "intake_ages", intake_ages))
            L.append(line(tok, "intake_amt", list(_g(md, "intakeAmt"))))
            frac = _g(md, "frac")
            for i in range(n):
                L.append(line(tok, f"frac{i + 1}", list(frac[i])))
            L.append(line(tok, "RBA", list(_g(md, "rba"))))
        else:
            src_ages = [years_to_days(a) for a in _g(md, "srcAgesYr")]
            L.append(line(tok, "source_ages", src_ages))
            src_amt = _g(md, "srcAmt")
            for i in range(n):
                L.append(line(tok, f"source_amt{i + 1}", list(src_amt[i])))
            L.append(line(tok, "RBA", list(_g(md, "rba"))))

    if int(_g(s, "iterate", 0)) == 1 and _g(cfg, "iter") is not None:
        it = _g(cfg, "iter")
        L.append(line("Iter", "media", [_g(it, "media")]))
        L.append(line("Iter", "subtype", [_g(it, "subtype")]))
        L.append(line("Iter", "dustsoil", [_g(it, "dustsoil")]))
        L.append(line("Iter", "targetbll", [_g(it, "targetbll")]))
        L.append(line("Iter", "precision", [_g(it, "precision")]))
        L.append(line("Iter", "maxiter", [_g(it, "maxiter")]))
        L.append(line("Iter", "agemin", [years_to_days(_g(it, "startAgeYr"))]))
        L.append(line("Iter", "agewidth", [years_to_days(float(_g(it, "endAgeYr")) - float(_g(it, "startAgeYr")))]))
        L.append(line("Iter", "metric", [_g(it, "metric")]))
        L.append(line("Iter", "gsd", [_g(it, "gsd")]))
        L.append(line("Iter", "tailfrac", [_g(it, "tailfrac")]))

    L.append("END")
    return "\r\n".join(L) + "\r\n"


# --------------------------------------------------------------------------- #
#  output parser
# --------------------------------------------------------------------------- #
def read_out_csv(path: str, max_points: int = 2500) -> Dict[str, Any]:
    with open(path, "r", newline="") as fh:
        reader = csv.reader(fh)
        rows = list(reader)
    if len(rows) < 2:
        raise ValueError("Output file is empty or incomplete.")

    header = [h.strip() for h in rows[0]]
    ncol = len(header)
    cols: Dict[str, List[float]] = {h: [] for h in header}
    for r in rows[1:]:
        if not r or all(c.strip() == "" for c in r):
            continue
        if len(r) < ncol:
            continue
        for c in range(ncol):
            try:
                cols[header[c]].append(float(r[c].strip()))
            except ValueError:
                cols[header[c]].append(0.0)

    years = cols["Years"]
    blood = cols["Cblood"]
    nrows = len(years)

    peak_bll = -1.0
    peak_age = 0.0
    total = 0.0
    peak_idx = 0
    for i in range(nrows):
        b = blood[i]
        total += b
        if b > peak_bll:
            peak_bll = b
            peak_age = years[i]
            peak_idx = i

    summary = {
        "rows": nrows,
        "peakBLL": round(peak_bll, 4),
        "peakAgeYr": round(peak_age, 3),
        "meanBLL": round(total / nrows, 4) if nrows else 0,
        "finalBLL": round(blood[-1], 4) if nrows else 0,
        "finalAgeYr": round(years[-1], 3) if nrows else 0,
    }

    stride = max(1, math.ceil(nrows / float(max_points)))
    keep = set(range(0, nrows, stride))
    keep.add(0)
    keep.add(nrows - 1)
    keep.add(peak_idx)
    idx = sorted(keep)

    series: Dict[str, List[float]] = {}
    for h in header:
        if h in ("Timestep", "Days", "Years"):
            continue
        series[h] = [round(cols[h][i], 6) for i in idx]
    x_years = [round(years[i], 5) for i in idx]

    return {"columns": header, "xYears": x_years, "series": series, "summary": summary}
